---
title: "National calculations and charts - Italy - COVID-19 Epidemic"
author: "Marcelo Eduardo Redoschi"
output: html_document
---

```{r echo=FALSE, message=FALSE}
library(readr)
library(lubridate)
library(dplyr)
library(markdown)
library(ggplot2)
source("helper_functions.R")
main_dir <-
file.path(getwd(), "..") # Project's main directory (top level)
datasets_path <-
file.path(main_dir, "Protezione-Civile-Dataset", "COVID-19")
csv_exports_dir <- file.path(main_dir, "csv_exports") 
if (!dir.exists(csv_exports_dir)) {dir.create(csv_exports_dir)}
```

```{r echo=FALSE, message=FALSE}
start_time<-Sys.time()
```

**`r format(start_time, "%a %d %b %Y %X %Z")`**

#### Based on the Protezione Civile Dataset
*Source: dpc-covid19-ita-andamento-nazionale.csv, own calculations*

```{r echo=FALSE, message=FALSE}
national_csv_fname <-
  file.path(
  datasets_path,
  "dati-andamento-nazionale",
  "dpc-covid19-ita-andamento-nazionale.csv"
  )
  dpc_covid19_ita_national <-
  import_csv(national_csv_fname)
  national <- dpc_covid19_ita_national
```

```{r echo=FALSE, message=FALSE}
national<-translated_national_column_names(dpc_covid19_ita_national)
national$dt<-as.Date(ymd_hms(national$data))
national$data<-NULL 
nat_expanded<-national
indicators<-c("total_cases","intensive_care","hospitalized_with_symptoms","home_isolation","total_discharged_healed","total_deceased","tests","new_positives","positives_remaining")

for (i in 1:length(indicators)) { 
  
nat_expanded<-expand_dt_columns(nat_expanded, "nation", indicators[i])
}  

write.csv(nat_expanded,file.path(csv_exports_dir,"nat_expanded.csv"))
national<-arrange(national, dt)
```

```{r echo=FALSE, message=FALSE}

most_recent_dt <- max(national$dt)
earliest_dt <- min(national$dt)
num_days <- most_recent_dt - earliest_dt

deltas_nat <- select(national, dt, all_of(indicators))

# Fill first delta row with zeros
for (k in 1:length(indicators)) {
deltas_nat[1, 1 + k] <- 0
}

# Start from the second row

for (i in 1:num_days) {
  start_dt <- earliest_dt + i
  finish_dt <- start_dt + 1
  
  for (j in 1:length(indicators)) {
    deltas_nat[1+i, 1 + j] <-
      calculate_delta(nat_expanded, indicators[j], start_dt-1, finish_dt-1)
    
    
  }
  
}

deltas_nat$hospitalized_total <-
  deltas_nat$hospitalized_with_symptoms + deltas_nat$intensive_care

df_col_names <- colnames(deltas_nat)

column_indices_to_mark_as_delta <-
  grep("dt", df_col_names, invert = TRUE) # i.e. excluding dt

column_names_to_mark_as_delta <-
  colnames(deltas_nat)[column_indices_to_mark_as_delta]

for (i in 1:length(column_names_to_mark_as_delta)) {
  original_column_name <- column_names_to_mark_as_delta[i]
  delta_column_name <- paste(original_column_name, "delta", sep = "_")
  df_col_names <-
    gsub(original_column_name, delta_column_name, df_col_names)
  
}

deltas_nat_labelled <- deltas_nat

colnames(deltas_nat_labelled) <- df_col_names

```

```{r echo=FALSE, message=FALSE}
nat_calc <- inner_join(national, deltas_nat_labelled, by = 'dt')
nat_calc$tests_per_new_positives <-
nat_calc$tests_delta / nat_calc$new_positives
nat_calc$total_tests_per_cases_ratio <-
nat_calc$tests / nat_calc$total_cases
```

```{r echo=FALSE, message=FALSE}

nat_calc$positives_remaining_previous <-
  nat_calc$positives_remaining - nat_calc$positives_remaining_delta

  #identical(nat_calc$positives_remaining_delta, nat_calc$num_positives_variation)

  nat_calc$positives_remaining_percent_delta <-
  nat_calc$positives_remaining_delta / nat_calc$positives_remaining_previous *
  100
  nat_calc$deceased_per_positives_day_before_ratio <-
  nat_calc$total_deceased_delta / nat_calc$positives_remaining_previous *
  100
  nat_calc$discharged_healed_per_positives_day_before_ratio <-
  nat_calc$total_discharged_healed_delta / nat_calc$positives_remaining_previous *
  100
  
```

```{r echo=FALSE}
nat_fatalities <-
  select(nat_calc,
  total_deceased_delta,
  total_deceased,
  total_cases,
  new_positives,
  dt,
  positives_remaining_delta)
  nat_fatalities$rate <-
  nat_fatalities$total_deceased / nat_fatalities$total_cases * 100
  nat_fatalities <-
  select(
  nat_fatalities,
  dt,
  new_positives,
  total_deceased_delta,
  total_cases,
  total_deceased,
  rate,
  positives_remaining_delta
  )
  col_names <- colnames(nat_fatalities)
  intl_col_names <- gsub("new_positives", "new_cases", col_names)
  intl_col_names <-
  gsub("positives_remaining_delta", "net_effect", intl_col_names)
 # intl_col_names <- gsub("rate", "fatality_rate", intl_col_names)
  intl_col_names <- gsub("total_deceased_delta", "fatalities", intl_col_names)
  colnames(nat_fatalities) <- intl_col_names
  
 nat_fatalities$dt<-as.Date(nat_fatalities$dt,format='%Y-%m-%d')
 nat_fatalities$rate<-round(nat_fatalities$rate, digits=2)
 
```

```{r fig.height=5, fig.width=10, echo=FALSE}
chart1_title <-
  paste('Total cases', format(min(national$dt), "%d %b"), "-", format(max(national$dt), "%d %b %Y"))
  
  chart1 <-
  ggplot(national, aes(y = log10(total_cases), x = dt)) + geom_line(color =
  "#40B35A", linetype = 2) + ggtitle(chart1_title) + ylab("Logarithmic scale") +
  xlab("Date")
  
  print(chart1)
```
```{r fig.height=5, fig.width=10, echo=FALSE}
chart2_title <-
  paste('Total fatalities',
  format(min(national$dt), "%d %b"),
  "-",
  format(max(national$dt), "%d %b %Y"))
  
  chart2 <-
  ggplot(nat_fatalities, aes(y = log10(total_deceased), x = dt)) + geom_line(color =
  "#98234a") + ggtitle(chart2_title) + ylab("Logarithmic scale") + xlab("Date")
  
  print(chart2)

```

```{r echo=FALSE}  
  nat_fatalities$dt<-format(nat_fatalities$dt,'%d/%m')  
  print(nat_fatalities)
```
*Net effect = positives remaining delta (i.e. after accounting for the people discharged from hospital or healed who were in isolation)*.

*Rate = mortality percent rate (total deceased / total cases).*

```{r fig.height=5, fig.width=10, echo=FALSE}

chart3_title <-
  paste(
  'Remaining active cases (daily change)',
  format(min(national$dt), "%d %b"),
  "-",
  format(max(national$dt), "%d %b %Y")
  )
  
  chart3 <-
  ggplot(nat_calc,
  aes(y = deceased_per_positives_day_before_ratio, x = dt)) + geom_line(color =
  "orange") + ggtitle(chart3_title) + xlab("Date") +
  ylab("In thousands")
  print(chart3)
  
```

```{r fig.height=5, fig.width=10, echo=FALSE}

chart3_supplemental_title <-
  paste('Positives remaining delta (after fatalities and discharged or healed)',
  format(min(national$dt), "%d %b"),
  "-",
  format(max(national$dt), "%d %b %Y")
  )
  
  chart3_supplemental <-
  ggplot(data=nat_calc)+ geom_line(aes(y = positives_remaining_delta, x = dt),color =
  "#2FA0D6") + ggtitle(chart3_supplemental_title) + xlab("Date") +
  ylab("people")
  print(chart3_supplemental)
  
```
```{r echo=FALSE}
nat4 <-
  select(
  nat_calc,
  dt,
  positives_remaining_previous,
  total_deceased_delta,
  total_discharged_healed_delta,
  deceased_per_positives_day_before_ratio,
  discharged_healed_per_positives_day_before_ratio
  )
  nat4$discharged_or_healed_to_deceased_ratio <-
  nat4$discharged_healed_per_positives_day_before_ratio / nat4$deceased_per_positives_day_before_ratio
```

```{r fig.height=5, fig.width=10, echo=FALSE, message=FALSE}

chart4_title <-
  paste(
  'Fatalities per active cases on the previous day',
  format(min(national$dt) + 1, "%d %b"),
  "-",
  format(max(national$dt), "%d %b %Y")
  )
  
  chart4 <-
  ggplot(nat4, aes(y = deceased_per_positives_day_before_ratio, x = dt)) +
  geom_line(color = "red", linetype = 2) + ggtitle(chart4_title) + xlab(paste(format(min(nat4$dt), "%d %b"), "-", format(max(nat4$dt), "%d %b %Y"))) +
  ylab("%")
  print(chart4)
  
```

```{r fig.height=5, fig.width=10, echo=FALSE}
    
chart5_title <-
  paste(
  'Discharged or healed per positive cases on the previous day',
  format(min(national$dt) + 1, "%d %b"),
  "-",
  format(max(national$dt), "%d %b")
  )
  
  
  chart5 <-
  ggplot(nat4,
  aes(y = discharged_healed_per_positives_day_before_ratio, x = dt)) + geom_line(color =
  "green") + ggtitle(chart5_title) + xlab("Date") + ylab("Proportion")
  print(chart5)
```


```{r fig.height=5, fig.width=10, echo=FALSE, message=FALSE, warning=FALSE}

chart6_title <-
  paste('Active cases remaining the day before per each healed or discharged')
  
  chart6 <-
  ggplot(nat4,
  aes(y = positives_remaining_previous / total_discharged_healed_delta, x =
  dt)) + geom_line(color = "purple", linetype = 5) + ggtitle(chart6_title) +
  xlab(paste(format(min(national$dt) + 1, "%d %b"), "-", format(max(national$dt), "%d %b %Y"))) +
  ylab("Proportion (smaller numbers are better)")
  print(chart6)
```


```{r fig.height=5, fig.width=10, echo=FALSE, message=FALSE, warning=FALSE}
    
chart7_title <-
  paste(
  'Fatalities per discharged or healed proportion'
  ,format(min(nat4$dt), "%d %b"),
  "-",
  format(max(nat4$dt), "%d %b %Y")
  )
  
  chart7 <-
  ggplot(nat4,
  aes(y = as.numeric(total_deceased_delta / total_discharged_healed_delta), x = dt)) +
  geom_line(color = "#7D2860") + ggtitle(chart7_title) + xlab("Date") + ylab("Lower figures are better")
  print(chart7)
```



```{r echo=FALSE, message=FALSE, warning=FALSE}
#print(select(nat4, dt, discharged_or_healed_to_deceased_ratio))
#summary(nat4$discharged_or_healed_to_deceased_ratio)
```


```{r echo=FALSE, message=FALSE}
nat5 <-
  select(
  nat_calc,
  dt,
  total_discharged_healed,
  total_deceased,
  positives_remaining,
  total_cases
  )
  nat5$inactive_discharged_healed_deceased <-
  nat5$total_discharged_healed + nat5$total_deceased
  nat5$active <-
  nat5$total_cases - nat5$inactive_discharged_healed_deceased
  nat5$pos <- backlog_dt(nat5, nat5$inactive_discharged_healed_deceased)
  
  nat6 <-
  select(nat5,
  dt,
  inactive_discharged_healed_deceased,
  positives_remaining,
  total_cases)
  
  nat6$trailing_dt <- nat6$dt
  
  for (i in 1:nrow(nat5)) {
  x <- nat5[i, ]$inactive_discharged_healed_deceased
  y <- backlog_dt(nat5, x)
  #	print(paste(i, y))
  nat6$trailing_dt[i] <- y
  nat6$num_days_trailing <- nat6$dt - nat6$trailing_dt
  }
```

```{r echo=FALSE, message=FALSE}

```



```{r fig.height=5, fig.width=10, echo=FALSE}
chart8_title <-
  paste('Intensive care (in red), hospitalized with symptoms and home isolation daily changes',
  format(min(national$dt), "%d %b"),
  "-",
  format(max(national$dt), "%d %b %Y")
  )
  
  chart8 <-
  ggplot(data=deltas_nat_labelled) + geom_line(aes(y = intensive_care_delta, x = dt),color = "red") + geom_line(aes(y = home_isolation_delta, x = dt),color = "orange") + geom_line(aes(y = hospitalized_with_symptoms_delta, x = dt),color = "yellow", size=2) + 
   ggtitle(chart8_title) + xlab("Date") + ylab("people")

  print(chart8)
  
```

```{r echo=FALSE, message=FALSE}
nat_calc<-arrange(nat_calc,dt)
num_observations<-nrow(nat_calc) # i.e. days recorded
first_day<-min(nat_calc$dt)

nat_trailing<-select(nat_calc, dt, positives_remaining, new_positives)

nat_trailing$days<-NA 

for (k in 1:num_observations) {
 
  current_day<-as.Date(first_day+k-1)
  num_days_trailing <- num_days_trailing_on_dt(nat_calc,
           current_day,
           "positives_remaining",
           "new_positives")

    nat_trailing$days[k] <- num_days_trailing 
    
} 


chart9_revised_title <-
  paste("Positives remaining vs. new positives (retrospective calculations)")
  
  chart9_revised <-
  ggplot(data=nat_trailing)+
  geom_line(aes(y = days, x = dt),color = "darkblue") + ggtitle(chart9_revised_title) + xlab(paste(format(min(nat_trailing$dt), "%d %b"),
  "-",
  format(max(nat_trailing$dt), "%d %b %Y"))) + ylab("Approximate number of days in the past")
  print(chart9_revised)
  nat_trailing$dt<-format(nat_trailing$dt,'%d/%m')  
  print(nat_trailing)
```

```{r echo=FALSE, message=FALSE}
write.csv(nat_calc, file.path(csv_exports_dir, "nat_calc.csv"))
```
---
```{r echo=FALSE, message=FALSE}
finish_time<-Sys.time()
running_time<-as.POSIXct(finish_time)-as.POSIXct(start_time)
running_time<-paste(round(running_time, digits=3),"seconds")
```
*Processing time: `r running_time`*

---
